# Generated by Django 3.2.4 on 2021-06-13 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Credencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCuenta', models.CharField(max_length=15)),
                ('usuarioCuenta', models.CharField(max_length=15)),
                ('contraseña', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=25)),
                ('Usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestorContraseñas.usuario')),
            ],
        ),
    ]
